### ISSUE TITLE
Loading OS-Windows on Linux

### ISSUE THREAD

**Issue by labordep** [astares/Pharo-OS-Windows#9]
Hi @astares,
I'm trying to load all Pharo-OS-xxx projects into an unique Pharo image.
The idea is to build ready to use development images for our developpers with the source-code of all OS inside. It will simplify our workflow to have only one reference Smalltalk image.

I started to load a baseline with OS-Windows on a Linux OS using SmalltalkCI, but I have this error:
![image](https://github.com/user-attachments/assets/a0e527f6-f643-4ea8-8128-33087acd7e00)

I think this is normal to have errors, probably anyone haven't the idea to do that :) but before to work on it my question is: do you know if this is possible to load all Pharo-OS-xxx in a same image to rull them all? Or maybe this is not a good idea or not possible due to a design or architecture reason?

Thanks for your help :)

**Comment by astares** [comment]
@labordep  sorry for the late reply. 
- is not a good idea, also the code for Windows would be useless on Linux or iOS
- thats one reason why they are separate projects and loadable independently

Metacello allows to selectively load - you could address this by using conditional checks 
within your BaselineOf.

**Comment by labordep** [comment]
Hi @astares thanks for your answer!
I will work on a top layer to adress "common" functions with the same API. 
If it's make sens...

**Comment by astares** [comment]
@labordep Yes, to some extent it is possible to define good abstractions and wrap similar functionality behind a common API. As soon as it comes to specific features for sure that's not possible anymore - Windows has for instance much more to offer than what is wrapped at the moment.

There seem to be not much interest on "Win" or platform specific parts and I unfortunately can not spend my spare time endlessly. Nonetheless I designed the packages in a way they can live "below" such a generalized common layer.

**Comment by labordep** [comment]
Ok! Good news :)
Basically our need is using clipboard or opening file browser windows... not very low level but need to have a single way OS agnostic to use for our developpers. 
We will start to propose a project. If you are interessted, I will ask you for opinions :)

**Comment by astares** [comment]
@labordep For this you do not need any specific packages as we already provide this in the **STANDARD Pharo image** and it should work on all the primary platforms already. If not it is a bug of the "out-of-the-box" Pharo and should be fixed there.

1. Opening a file browser window
if you have a file reference you can send #openInOSFileBrowser 
```Smalltalk
Smalltalk imageDirectory openInOSFileBrowser 
```

2. Setting or retrieving Clipboard contents
- you can set and get the clipboard contents using #clipboardText/#clipboardText:
```Smalltalk
Clipboard clipboardText: 'hello'
```

3. Open a web browser
- you can open a web browser by giving a URL
```Smalltalk
WebBrowser openOn: 'https://www.pharo.org'
```
4. Handle environment variables
- as for the OSEnvironment subclass instance and use it like a dictionary:
```Smalltalk
Smalltalk os environment keys
```

5. Run a command
- run a command for the OS
```Smalltalk
LibC runCommand: '...'
```

**Comment by labordep** [comment]
Thanks a lot!
